name: teaspoon
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - capnproto=1.0.2
  - gsl=2.7
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libsqlite=3.46.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - mash=2.3
  - ncurses=6.5
  - openssl=3.3.2
  - pip=24.2
  - python=3.12.6
  - rasusa=2.1.0
  - readline=8.2
  - setuptools=75.1.0
  - tk=8.6.13
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.2.6
  - zlib=1.3.1
